# These are supported funding model platforms

github: avenbreaks # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: avenbreaks # Replace with a single Patreon username
open_collective: avenbreaks # Replace with a single Open Collective username
ko_fi: avenbreaks # Replace with a single Ko-fi username
tidelift: avenbreaks # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: avenbreaks # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: avenbreaks # Replace with a single Liberapay username
issuehunt: avenbreaks # Replace with a single IssueHunt username
otechie: avenbreaks # Replace with a single Otechie username
lfx_crowdfunding: avenbreaks # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: "https://gitcoin.co/grants/6541/chainflag"
