steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/images/eth-faucet:$_TAG
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/images/eth-faucet:$COMMIT_SHA
      - --dockerfile=Dockerfile
      - --cache=true
      - --cache-ttl=48h